/**
 * Tamada Clinic & SDX Dental — Data-Driven Organization Taxonomy v2.0
 * Source: Data_Driven_Org_By Nexus OS.pdf (June 2026)
 * Single Source of Truth for L0 Data Dictionary
 */
import type { DictionarySeed } from './workbook-template'

export type DataPriority = 'basic' | 'intermediate' | 'advanced'
export type DataEntity = 'tamada' | 'sdx' | 'franchise' | 'all'

export type TamadaDictionarySeed = DictionarySeed & {
  domain: string
  priority: DataPriority
  entity: DataEntity
  nexus_layer: string
}

function m(
  domain: string,
  priority: DataPriority,
  entity: DataEntity,
  nexus_layer: string,
  layer: DictionarySeed['layer'],
  metric_key: string,
  name: string,
  definition: string,
  formula: string,
  source: string,
  owner: string,
  security_tier: string,
  update_frequency: string,
  examples?: string,
): TamadaDictionarySeed {
  return {
    domain, priority, entity, nexus_layer, layer, metric_key, name, definition, formula, source, owner, security_tier, update_frequency, examples,
  }
}

/** 59 canonical metrics — Tamada v2.0 PDF */
export const TAMADA_DICTIONARY_SEED: TamadaDictionarySeed[] = [
  // ── 1. CEO ──
  m('ceo', 'basic', 'all', 'L6', 'Performance', 'corporate_okr_kpi', 'Corporate OKR & KPI',
    'เป้าหมายองค์กรระดับบริษัทที่ตกลงกันไว้รายปี/รายไตรมาส',
    'OKR: Objective + 3–5 Key Results · KPI: lag/lead indicator รายไตรมาส',
    'CEO Office + Strategy Planning Document', 'CEO (พี่นัท)', 'T1', 'quarterly'),
  m('ceo', 'basic', 'all', 'L6', 'Performance', 'department_kpi', 'Department KPI',
    'ตัวชี้วัดระดับแผนก — นิยาม + สูตร + Baseline + Target + Frequency',
    'แต่ละ KPI: นิยาม + สูตร + Baseline + Target + Frequency',
    'Department Head → Data Dictionary Template', 'C-Suite แต่ละสาย', 'T1', 'monthly'),
  m('ceo', 'basic', 'all', 'L5', 'People', 'individual_kpi', 'Individual KPI',
    'เป้าหมายรายบุคคล เชื่อม Skill Wallet (L4) และ Work Log (L5)',
    'achievement rate = actual / target × 100',
    'Work Log System (L5) + Performance Review', 'หัวหน้าแผนก + HR', 'T2', 'continuous'),
  m('ceo', 'intermediate', 'all', 'L6', 'Performance', 'organization_health_score', 'Organization Health Score',
    'คะแนนสุขภาพองค์กร real-time จาก 4 มิติ: People, Operations, Finance, Customer',
    'Weighted score จาก 4 dimension · น้ำหนักปรับได้ตาม priority',
    'Aggregated L0–L5 · คำนวณ daily', 'Nexus OS System · CEO viewer', 'T1', 'daily', 'Readiness dashboard'),

  // ── 2. Marketing ──
  m('marketing', 'basic', 'tamada', 'L0', 'Customer', 'repeated_customers', 'Repeated Customers',
    'ลูกค้าที่กลับมาใช้บริการซ้ำ (Monthly/Quarterly/Bi-Annually/Annually)',
    'Repeat Customer Count = unique customer_id ที่ transaction ≥ 2 ครั้งในช่วงเวลา',
    'TCS / POS transaction log', 'Chief Marketing', 'T1', 'daily'),
  m('marketing', 'basic', 'tamada', 'L0', 'Customer', 'customer_segmentation', 'Customer Segmentation',
    'จัดกลุ่มลูกค้า New/Active/At-Risk/Churned หรือ demographics',
    'RFM: Recency + Frequency + Monetary',
    'CRM / TCS transaction history', 'Chief Marketing', 'T1', 'weekly'),
  m('marketing', 'basic', 'tamada', 'L0', 'Customer', 'top_products', 'Top Products',
    'Treatment/บริการที่สร้างรายได้สูงสุด — Revenue, Volume หรือ Gross Margin',
    'Rank by Revenue, Volume, หรือ Gross Margin',
    'TCS / POS · แยก Medical และ Dental', 'Chief Marketing + Head of Medical/Dental', 'T1', 'monthly'),
  m('marketing', 'basic', 'tamada', 'L0', 'Customer', 'top_promotion', 'Top Promotion',
    'โปรโมชั่นที่ให้ผลตอบรับสูงสุด',
    'Promotion ROI = (Revenue - Cost) / Cost × 100 · Conversion = ซื้อ / รับรู้',
    'CRM + POS + LINE OA broadcast analytics', 'Chief Marketing', 'T1', 'monthly'),
  m('marketing', 'intermediate', 'tamada', 'L0', 'Customer', 'customer_retention_rate', 'Customer Retention Rate (30/60/90d)',
    'สัดส่วนลูกค้าที่กลับมาภายใน 30, 60, 90 วัน',
    'Retention = ลูกค้ากลับมา ÷ ลูกค้าทั้งหมด × 100 · per cohort',
    'TCS transaction log · ย้อนหลัง ≥ 90 วัน', 'Chief Marketing', 'T1', 'monthly'),
  m('marketing', 'intermediate', 'tamada', 'L0', 'Customer', 'new_vs_returning_ratio', 'New vs Returning Customer Ratio',
    'สัดส่วนลูกค้าใหม่ vs ลูกค้าเดิม',
    'New = customer_id ครั้งแรกในเดือน · Ratio = New ÷ Total × 100',
    'TCS / CRM · first-visit date', 'Chief Marketing', 'T1', 'monthly'),
  m('marketing', 'intermediate', 'tamada', 'L0', 'Customer', 'nps_csat', 'NPS / Customer Satisfaction',
    'Net Promoter Score และ CSAT',
    'NPS = % Promoters (9–10) − % Detractors (0–6) · CSAT = score ÷ responses × 100',
    'LINE OA survey · Google Review · feedback_2026.xlsx', 'Chief Marketing + Head of Operations', 'T1', 'weekly'),
  m('marketing', 'advanced', 'tamada', 'L0', 'Customer', 'customer_ltv', 'Customer Lifetime Value by Segment',
    'มูลค่ารวมที่ลูกค้าแต่ละกลุ่มสร้างตลอดความสัมพันธ์',
    'LTV = AOV × Purchase Frequency × Lifespan (months)',
    'TCS transaction history ≥ 12 เดือน', 'Chief Marketing · CFO ตรวจสูตร', 'T2', 'monthly'),
  m('marketing', 'basic', 'tamada', 'L0', 'Customer', 'campaign_roi', 'Campaign ROI',
    'ผลตอบแทนจากแคมเปญการตลาดแต่ละช่องทาง',
    'ROI = (Revenue from Campaign − Cost) ÷ Cost × 100',
    'CRM + POS + LINE OA broadcast analytics', 'Chief Marketing', 'T1', 'monthly'),
  m('marketing', 'intermediate', 'tamada', 'L0', 'Customer', 'customer_acquisition_cost', 'Customer Acquisition Cost (CAC)',
    'ต้นทุนเฉลี่ยต่อการได้ลูกค้าใหม่ 1 ราย',
    'CAC = Total Marketing Spend ÷ New Customers Acquired',
    'Marketing spend report + TCS first-visit log', 'Chief Marketing + CFO', 'T2', 'monthly'),

  // ── 3. Operations ──
  m('operations', 'basic', 'tamada', 'L3', 'Knowledge', 'sop_coverage', 'SOP Coverage',
    'ขั้นตอนมาตรฐานการทำงานทุก role — เก็บใน L3 Organizational Memory',
    'SOP Coverage Rate = role ที่มี SOP ÷ role ทั้งหมด × 100',
    'SOP Word/PDF → L3 Knowledge Framework', 'Head of Operations + Dept Head', 'T1', 'monthly'),
  m('operations', 'basic', 'tamada', 'L6', 'Operation', 'daily_readiness_score', 'Daily Readiness Score',
    'คะแนนความพร้อมสาขาก่อนเปิดบริการ',
    'Score = checklist ผ่าน ÷ total × 100 · ≥90% พร้อม, <80% alert',
    'Daily checklist LINE/Browser ก่อน 09:00', 'Branch Manager · Head of Ops aggregate', 'T1', 'daily'),
  m('operations', 'basic', 'tamada', 'L0', 'Operation', 'slot_utilization', 'Slot / Room Utilization Rate',
    'เปอร์เซ็นต์ slot ที่ถูกจองและใช้งานจริงต่อวัน',
    'Utilization = slot ใช้จริง ÷ slot เปิด × 100',
    'Booking system / TCS · real-time', 'Head of Operations', 'T1', 'daily'),
  m('operations', 'basic', 'tamada', 'L0', 'Operation', 'no_show_rate', 'No-show Rate + Late Cancel Rate',
    'อัตราลูกค้านัดแล้วไม่มา และยกเลิกกะทันหัน',
    'No-show = no-show ÷ booking × 100 · Late Cancel = cancel ภายใน 2 ชม.',
    'Booking system / TCS', 'Head of Operations + Chief Marketing', 'T1', 'daily'),
  m('operations', 'intermediate', 'tamada', 'L5', 'Performance', 'complaint_rate', 'Complaint Rate + Resolution Time',
    'จำนวน complaint ต่อ total cases และเวลาเฉลี่ยแก้ไข',
    'Complaint Rate = complaints ÷ cases × 100 · Resolution = close - open',
    'Complaint log / Work Log System', 'Head of Operations', 'T1', 'weekly'),
  m('operations', 'advanced', 'tamada', 'L0', 'Operation', 'treatment_completion_rate', 'Treatment Completion Rate vs Booking',
    'สัดส่วน booking ที่ทำ treatment ครบ vs cancel/incomplete',
    'Completion = completed ÷ total booked × 100',
    'TCS treatment record · status tracking', 'Head of Medical + Head of Operations', 'T2', 'daily'),

  // ── 4. Financial ──
  m('financial', 'basic', 'all', 'L0', 'Financial', 'revenue_cost_profit', 'Revenue / Cost / Profit',
    'รายได้รวม ต้นทุนรวม และกำไรสุทธิระดับ entity',
    'Gross Profit = Revenue - COGS · Net = Gross - OpEx - Tax',
    'TCS / BC365 / SDX Finance Report', 'CFO', 'T2', 'monthly'),
  m('financial', 'basic', 'all', 'L0', 'Financial', 'margin', 'Margin',
    'Gross Margin และ Net Margin แยกรายสาขาและรายบริษัท',
    'Gross Margin % = (Revenue - Direct Cost) ÷ Revenue × 100',
    'TCS / BC365 / SDX Finance Report', 'CFO', 'T2', 'monthly'),
  m('financial', 'basic', 'all', 'L0', 'Financial', 'ebitda', 'EBITDA',
    'กำไรก่อนหักดอกเบี้ย ภาษี ค่าเสื่อม และค่าตัดจ่าย',
    'EBITDA = Net Profit + Interest + Tax + D&A',
    'TCS / BC365 / SDX Finance Report', 'CFO', 'T2', 'monthly'),
  m('financial', 'basic', 'all', 'L0', 'Financial', 'branch_pnl', 'Branch P&L (Owned & Franchise)',
    'งบกำไรขาดทุนแยกรายสาขา owned และ franchise',
    'Branch P&L = Branch Revenue - Direct Cost - Allocated Overhead',
    'TCS / BC365 · franchisee report', 'CFO + Franchise Manager', 'T2', 'monthly'),
  m('financial', 'intermediate', 'all', 'L0', 'Financial', 'cash_flow_liquidity', 'Cash Flow + Liquidity',
    'กระแสเงินสดรายเดือนและสภาพคล่อง',
    'OCF = Net Income + Non-cash ± WC · Liquidity = Current Assets ÷ Liabilities',
    'TCS / BC365 / SDX Finance Report', 'CFO', 'T2', 'monthly'),
  m('financial', 'intermediate', 'tamada', 'L0', 'Financial', 'doctor_revenue', 'Doctor Revenue by Individual',
    'รายได้หัตถการในชื่อแพทย์แต่ละคน หักต้นทุนวัสดุ',
    'Doctor Revenue = Σ Procedure - Σ Material Cost · match doctor_id',
    'TCS + Inventory usage', 'CFO + Head of Medical', 'T2', 'daily'),
  m('financial', 'intermediate', 'all', 'L0', 'Financial', 'incentive_reconciliation', 'Incentive vs Revenue Reconciliation',
    'reconcile incentive จ่ายจริงกับยอดขาย',
    'Incentive % = Total Variable Pay ÷ Total Revenue × 100',
    'Payroll + BC365 Revenue', 'CFO + Chief HR', 'T2', 'monthly'),
  m('financial', 'intermediate', 'all', 'L0', 'Financial', 'cost_saving', 'Cost Saving',
    'ต้นทุนที่ประหยัดได้จากระบบและกระบวนการปรับปรุง',
    'Cost Saving = Baseline Cost − Current Cost',
    'BC365 / TCS cost report', 'CFO', 'T2', 'monthly', '12,450 บาท/เดือน'),

  // ── 5. People ──
  m('people', 'basic', 'all', 'L1', 'People', 'org_structure', 'Org Structure',
    'โครงสร้างองค์กร ~250 คน span of control',
    'Span of Control = ลูกน้อง ÷ หัวหน้า · benchmark 5–8',
    'HR System / Org Chart document', 'Chief HR', 'T1', 'monthly'),
  m('people', 'basic', 'all', 'L1', 'People', 'job_scope', 'Job Scope',
    'ขอบเขตงานแต่ละ position — input L4 Skill Wallet',
    'Completeness = % position ที่มี JD ครบ',
    'HR Documentation · JD ทุก department', 'Chief HR + Dept Head', 'T1', 'monthly'),
  m('people', 'basic', 'all', 'L4', 'People', 'skill_score', 'Skills Bank',
    'ทักษะพนักงานจาก Work Log จริง ไม่ใช่ self-report',
    'Skill Score = weighted(Work Log + KPI + Training)',
    'Work Log (L5) + Training + Performance Review', 'Chief HR', 'T2', 'continuous'),
  m('people', 'basic', 'all', 'L1', 'People', 'hiring_onboarding_status', 'Hiring & Onboarding Status',
    'สถานะสรรหาและ onboarding รายตำแหน่ง',
    'Time-to-Fill · Onboarding Progress = % checklist เสร็จ',
    'HR Recruitment Tool + HR System', 'Chief HR', 'T1', 'weekly'),
  m('people', 'basic', 'all', 'L1', 'People', 'people_demographic', 'People Demographic',
    'อายุ เพศ อายุงาน การศึกษา — aggregate stats',
    'average age, tenure distribution, gender ratio',
    'HR System', 'Chief HR', 'T2', 'monthly'),
  m('people', 'basic', 'all', 'L1', 'People', 'employee_profile', 'Employee Profile',
    'ชื่อ ชื่อเล่น อีเมล รูป — Employee Workspace L5',
    'ครบ 100% สำหรับพนักงาน active',
    'HR System / onboarding form', 'Chief HR', 'T1', 'monthly'),
  m('people', 'basic', 'all', 'L0', 'People', 'payroll_benefit', 'Payroll & Benefit',
    'โครงสร้างเงินเดือนและสวัสดิการ',
    'Total Labor Cost = Base + Variable + Benefits + SS + PF',
    'Payroll system', 'Chief HR + CFO', 'T3', 'monthly'),
  m('people', 'intermediate', 'all', 'L4', 'People', 'talent_profile', 'Talent Profile + Development Plan',
    'performance history, potential, succession plan',
    '9-box = Performance × Potential · Succession Readiness %',
    'Performance Review + Manager assessment', 'Chief HR · CEO C-Suite succession', 'T2', 'quarterly'),
  m('people', 'intermediate', 'all', 'L4', 'People', 'turnover_attrition_risk', 'Turnover + Attrition Risk',
    'อัตราลาออกรายแผนกและ AI attrition risk จาก Work Log',
    'Turnover = ลาออก ÷ headcount × 100',
    'HR System + Work Log (L5)', 'Chief HR', 'T2', 'monthly'),
  m('people', 'intermediate', 'tamada', 'L1', 'Operation', 'doctor_availability', 'Doctor Availability Calendar',
    'ปฏิทินแพทย์แยกสาขา วันทำงาน/ลา/หยุด',
    'Doctor Coverage = วันมีแพทย์ ÷ วันเปิด × 100',
    'HR leave + Branch schedule', 'Head of Medical + Chief HR', 'T1', 'weekly'),
  m('people', 'intermediate', 'all', 'L4', 'People', 'performance_review_trend', 'Performance Review History',
    'ประวัติการประเมินและ rating trend',
    'Performance = KPI 60% + Behavior 40% · Trend MoM',
    'Performance Review + Work Log (L5)', 'Dept Head + Chief HR', 'T2', 'quarterly'),
  m('people', 'intermediate', 'all', 'L1', 'People', 'probation_tracking', 'Probation Tracking',
    'สถานะ pass/fail ทดลองงานพร้อมเหตุผล',
    'Probation Pass Rate = ผ่าน ÷ hired × 100',
    'HR System · ทุก 90 วัน', 'Chief HR + Dept Head', 'T2', 'monthly'),
  m('people', 'advanced', 'all', 'L1', 'People', 'warning_disciplinary', 'Warning / Disciplinary Record',
    'ประวัติ warning และ disciplinary action',
    'Warning Rate = warnings ÷ headcount × 100',
    'HR disciplinary records', 'Chief HR · HR + CEO + Legal', 'T3', 'monthly'),
  m('people', 'intermediate', 'tamada', 'L4', 'People', 'new_doctor_ramp', 'New Doctor Ramp-up (Day 1–30)',
    'พัฒนาการหมอใหม่ช่วง 30 วันแรก — ลูกค้าเก่าและเคสที่เชี่ยวชาญ',
    'Ramp Score = repeat patients + specialized cases ÷ target × 100',
    'TCS + CRM · doctor onboarding checklist', 'Head of Medical + Chief HR', 'T2', 'monthly', 'วันที่ 30: 24 เคสซ้ำ'),

  // ── 6. Medical ──
  m('medical', 'basic', 'tamada', 'L0', 'Financial', 'treatment_revenue_category', 'Treatment Revenue by Category',
    'รายได้แยก Botox, Filler, Laser, Whitening, Skincare, Others',
    'Revenue by Category · Contribution % = category ÷ total × 100',
    'TCS treatment record · price list', 'Head of Medical + CFO', 'T1', 'daily'),
  m('medical', 'basic', 'tamada', 'L0', 'Performance', 'top_doctor_revenue', 'Top Doctor by Revenue + Patient Count',
    'แพทย์รายได้สูงสุดและ patient count',
    'Doctor Revenue · Patient Count = unique patient_id per doctor per month',
    'TCS · doctor_id', 'Head of Medical · CEO/CFO', 'T2', 'monthly'),
  m('medical', 'basic', 'tamada', 'L0', 'Operation', 'treatment_volume', 'Treatment Volume (Cases)',
    'จำนวนเคสหัตถการ aesthetic รายวัน/รายสาขา',
    'Case Count = Σ completed treatments · per branch per day',
    'TCS treatment record', 'Head of Medical + Head of Operations', 'T1', 'daily'),
  m('medical', 'advanced', 'tamada', 'L0', 'Customer', 'patient_record', 'Patient Record (T3 / PDPA)',
    'ข้อมูลคนไข้และประวัติการรักษา — ข้อมูลดิบ ไม่ใช่ตัวเลขสรุป',
    '— (raw clinical data · pseudonymize before analytics)',
    'TCS / HIS · encrypted storage', 'Head of Medical · PDPA officer', 'T3', 'continuous', 'เข้ารหัส + consent'),

  // ── 7. Dental (SDX) ──
  m('dental', 'basic', 'sdx', 'L0', 'Financial', 'dental_revenue_type', 'Dental Revenue by Type',
    'รายได้แยกจัดฟัน ฟอกสี อุด ถอน Implant Veneer',
    'Revenue by Type = Σ ยอดขาย dental treatment ประเภทนั้น',
    'SDX Dental MCS', 'Head of SDX Dental + CFO', 'T1', 'daily'),
  m('dental', 'intermediate', 'sdx', 'L0', 'Financial', 'dental_case_mix', 'Case Mix Ratio (Cosmetic vs Restorative)',
    'สัดส่วน cosmetic vs restorative dental',
    'Cosmetic % = Cosmetic Revenue ÷ Total Dental × 100 · target ≥60%',
    'SDX Dental MCS · treatment_type', 'Head of SDX Dental', 'T1', 'monthly'),
  m('dental', 'intermediate', 'sdx', 'L0', 'Operation', 'chair_utilization', 'Chair Utilization per Branch',
    'เปอร์เซ็นต์การใช้ dental chair · 1 slot = 60 นาที',
    'Chair Utilization = เวลาใช้จริง ÷ เวลาเปิด × 100',
    'SDX Booking + TCS', 'Head of SDX Dental + Head of Operations', 'T1', 'daily'),
  m('dental', 'advanced', 'all', 'L0', 'Customer', 'aesthetic_dental_crosssell', 'Aesthetic × Dental Cross-sell Rate',
    'อัตราลูกค้าใช้ทั้ง Aesthetic และ Dental',
    'Cross-sell = ลูกค้าใช้ทั้งสอง ÷ total customers × 100 · ต้อง PDPA consent',
    'Match customer_id Tamada TCS + SDX MCS', 'Chief Marketing + Head of SDX Dental', 'T2', 'monthly'),

  // ── 8. IT ──
  m('it', 'basic', 'all', 'L0', 'Operation', 'system_uptime', 'System Uptime / Downtime Log',
    'uptime/downtime BC365, TCS, LINE OA, HIS',
    'Uptime % = (Total hours - Downtime) ÷ Total × 100 · SLA ≥99.5%',
    'System monitoring · IT log', 'Head of IT', 'T1', 'daily'),
  m('it', 'intermediate', 'all', 'L0', 'Knowledge', 'integration_status', 'Data Source Integration Status',
    'สถานะ sync HIS, POS, CRM, ERP → Nexus OS',
    'Integration Coverage = auto-sync sources ÷ total × 100 · target 100%',
    'IT inventory + Nexus ingestion log', 'Head of IT + Nexus Team', 'T1', 'weekly'),

  // ── 9. Warehouse ──
  m('warehouse', 'basic', 'tamada', 'L0', 'Operation', 'remaining_stock', 'Remaining Stock',
    'stock คงเหลือแยกรายสาขา',
    'Days of Stock = Remaining ÷ Avg Daily Usage · Reorder = Lead Time × Daily Usage',
    'Warehouse management / Purchasing', 'Warehouse & Purchasing Manager', 'T1', 'daily'),
  m('warehouse', 'basic', 'tamada', 'L0', 'Operation', 'historical_usage', 'Historical Usage by Item',
    'การใช้วัสดุย้อนหลังแยก item และ treatment type',
    'Avg Daily Usage = Σ ใช้ ÷ จำนวนวัน',
    'Warehouse + TCS treatment record', 'Warehouse Manager + Head of Medical', 'T1', 'weekly'),
  m('warehouse', 'intermediate', 'tamada', 'L0', 'Operation', 'stockout_rate', 'Stock-out Rate',
    'อัตราวัสดุหมดสต็อกที่กระทบการให้บริการ',
    'Stock-out Rate = stockout events ÷ total SKUs × 100',
    'Warehouse management system', 'Warehouse & Purchasing Manager', 'T1', 'weekly'),
  m('warehouse', 'intermediate', 'tamada', 'L0', 'Operation', 'inventory_turnover', 'Inventory Turnover',
    'ความเร็วหมุนเวียนสต็อกวัสดุ',
    'Turnover = COGS ÷ Average Inventory',
    'Warehouse + BC365 cost data', 'Warehouse Manager + CFO', 'T2', 'monthly'),

  // ── 10. Franchise ──
  m('franchise', 'basic', 'franchise', 'L6', 'Performance', 'franchise_kpi_benchmark', 'Franchise KPI vs Benchmark',
    'KPI franchisee เทียบมาตรฐาน HQ',
    'KPI Gap = Actual - Benchmark · Franchise Score = weighted KPI',
    'Franchisee monthly report + HQ benchmark', 'Franchise Manager + CFO', 'T2', 'monthly'),
  m('franchise', 'intermediate', 'franchise', 'L0', 'Financial', 'royalty_payment_status', 'Royalty Payment Status',
    'สถานะจ่าย royalty on-time/overdue/disputed',
    'Royalty Receivable = Franchise Revenue × Royalty Rate · Overdue >30 วัน',
    'Finance + Franchise agreement', 'CFO + Franchise Manager', 'T2', 'monthly'),
  m('franchise', 'advanced', 'franchise', 'L5', 'Performance', 'brand_compliance_score', 'Brand Compliance Score',
    'compliance franchisee กับ brand standards',
    'Compliance = Σ (passed ÷ total) × weight × 100',
    'Work Log L5 + Mystery shopper + Training', 'Franchise Manager + Chief Marketing', 'T1', 'monthly'),
]

export const TAMADA_DOMAIN_SUMMARY = [
  { id: 'ceo', label: 'CEO — Strategic Command', count: 4, layer: 'L6' },
  { id: 'marketing', label: 'Marketing — Customer Intelligence', count: 10, layer: 'L0 Customer' },
  { id: 'operations', label: 'Operations — Daily Readiness', count: 6, layer: 'L5/L6' },
  { id: 'financial', label: 'Financial & Accounting', count: 8, layer: 'L0 Financial' },
  { id: 'people', label: 'People — Human Capital', count: 14, layer: 'L1/L4' },
  { id: 'medical', label: 'Medical — Aesthetic', count: 4, layer: 'L0 Operation' },
  { id: 'dental', label: 'Dental — SDX Division', count: 4, layer: 'L0 Financial/Op' },
  { id: 'it', label: 'IT — Data Infrastructure', count: 2, layer: 'L0 Taxonomy' },
  { id: 'warehouse', label: 'Warehouse & Purchasing', count: 4, layer: 'L0 Operation' },
  { id: 'franchise', label: 'Franchise — Partner Performance', count: 3, layer: 'L1/L6' },
] as const

export function getTamadaMetricsByDomain(domain?: string) {
  if (!domain) return TAMADA_DICTIONARY_SEED
  return TAMADA_DICTIONARY_SEED.filter(m => m.domain === domain)
}

export function getTamadaMetricsByPriority(priority?: DataPriority) {
  if (!priority) return TAMADA_DICTIONARY_SEED
  return TAMADA_DICTIONARY_SEED.filter(m => m.priority === priority)
}
